name = "mon"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "app-mon-db"
database_id = "89717d93-ecc1-48a4-9192-1160bd79b2d6"

[[vectorize]]
binding = "VECTORIZE"
index_name = "mon-index"

[ai]
binding = "AI"